### ISSUE TITLE
[PROPOSAL] Follow a git workflow to make things clear

### ISSUE THREAD

**Issue by dustbyte** [evadot/millipede#11]
I think at this point the project should embrace a git workflow such as [nvie/gitflow](nvie/gitflow) to enhance and lighten the distributed maintenance process.

**Comment by tusbar** [comment]
no

**Comment by tusbar** [comment]
:-1:

**Comment by rockyluke** [comment]
:-1:

**Comment by dustbyte** [comment]
:-1:  youselves

**Comment by evadot** [comment]
I don't like the gitflow model. It's too complicated when it shouldn't.
The branch per feature is what I use day to day.
Dev on a branch then merge to master.
The master branch is "unstable" or "dev" or whatever you want to call it.
At some point we tag to notify a release.
For me it's simple and efficient.

What do you guys think ?

**Comment by dustbyte** [comment]
Personally I think master, as a "welcoming" branch should always be stable. Therefore cloning from it gives the latest stable version.

It's just a matter of release management, regarding github development flow.

**Comment by tusbar** [comment]
:-1:

**Comment by tusbar** [comment]
release management has nothing to do with branching. if you package using git, it's your problem.

**Comment by dustbyte** [comment]
I think you're wrong and you should feel bad for that.

**Comment by rockyluke** [comment]
:-1:

**Comment by tusbar** [comment]
:-1:

**Comment by evadot** [comment]
:-1:

**Comment by evadot** [comment]
We can close this right ?

**Comment by dustbyte** [comment]
Pays de Galles indépendant !

**Comment by tusbar** [comment]
:-1:
